### ISSUE TITLE
installation fails silently

### ISSUE THREAD

**Issue by fgrunewald** [kain88-de/pbc_distances#1]
Dear kain88-de, 

I just tried installing this package, but although it installs and is importable, it is impossible to access the functions (e.g. pairwise_distance) associated with it. Except for the C++ compiler throwing a few warnings it doesn't give any error. The c++/c compiler is GCC version 5.4.0. Do you've any ideas what might have gone wrong?

Thanks!

**Comment by kain88-de** [comment]
The example in the README was a little bit too far into the future. The library can't yet auto-pick the best instruction set. I updated the readme to a workable example.  If you have MDAnalysis and mdtraj installed the `ipython benchmark.ipy` should run if the library is correctly installed.

If this still doesn't help it would be nice if you can post the output of the installation.

Please keep in mind that his is **alpha software** and meant as a **proof of concept**. Stable implementation of the distance calculations can be found in [MDAnalysis](https://www.mdanalysis.org/docs/documentation_pages/lib/distances.html#module-MDAnalysis.lib.distances)

If you need really fast distance calculations have a look at the [cellgrid](https://github.com/MDAnalysis/cellgrid) library.  This library is also still in development but due to using better algorithms it  outperform this one for large data sets. I use the following code to calculate all self-distances.  

```python
import numpy as np
from scipy import sparse
from MDAnalysis.lib.distances import distance_array
import cellgrid


def self_distance(xyz, maxdist, box=None, nbins=5):
    """Calculate all distances between point pairs in xyz that are below maxdist.

    Parameters
    ----------
    xyz : array-like (N, 3)
        coordinates to build search for distances
    maxdist : float
        maximal distance to record in output
    box : array-like (optional)
        periodic boundary box
    nbins : int (optional)
        number of cells per dimension. A too high value can cause
        poor performance!


    Returns
    -------
    out : coo_matrix
         sparse matrix with all distances below maxdist

    Example
    -------
    >>> box = np.ones(3).astype(np.float32) * 100
    >>> a = np.random.uniform(low=0, high=box[0], size=(1000, 3)).astype(np.float32)
    >>> maxdist = 1
    >>> d = distances(a, maxdist, box)

    """
    xyz = np.asarray(xyz)

    binsize = (1. / nbins) * (xyz.max() - xyz.min())

    # always define a box for the cell grid to use!
    grid_box = box
    if grid_box is None:
        grid_box = np.ones(3) * (xyz.max() + 10)

    grid = cellgrid.CellGrid(grid_box, binsize, xyz)
    N = len(xyz)
    out = sparse.lil_matrix((N, N))

    for cell in grid:
        # check for particles in cell
        if len(cell) > 1:
            d = distance_array(cell.coordinates, cell.coordinates, box)
            i, j = np.where(d < maxdist)
            out[cell.indices[i], cell.indices[j]] = d[(i, j)]

        # check all neighbors
        for addr in cell.all_neighbours:
            other = grid[addr]
            if not other:
                continue
            d = distance_array(cell.coordinates, other.coordinates, box)
            i, j = np.where(d < maxdist)
            out[cell.indices[i], other.indices[j]] = d[(i, j)]

    return out.tocoo()
```

**Comment by fgrunewald** [comment]
Thanks, for the explanations and the cellgrid recommendation. I didn't realize this package was just in the alpha phase and indeed I'm looking for something faster than the current algorithm in MDAnanlysis. Since cellgrid seems to work fine, so I go with that one. I'll close the issue, but if you want someone from "outside" to install and maybe test this implementation let me know!

**Comment by kain88-de** [comment]
If you need speed up with MDAnalysis I recommend compiling it from source. We have flags `MDA_march=native’ to be enable aggressive optimization and I have seen more then factor 2 improvements in comparison to the conda packages. 

https://github.com/MDAnalysis/mdanalysis/blob/develop/package/setup.cfg
